<?php
$is_update = false;
if (isset($update))
    $is_update = true;
$title = !$is_update ? "Добавления задачи" : "Обновления задачи";
?>
<div class="form-input">
    <div class="bd-example">
        <form action="<?= !$is_update ? 'add-task' : 'update-task'.''; ?>" method="post" name="<?= !$is_update ? 'add-task' : 'update-task'; ?>">
            <h3><?= $title; ?></h3>
            <input id="id" name="id" class="form-control d-none" value="<?= $model->id; ?>"/>
            <div class="form-group">
                <label>Имя пользователя</label>
                <input id="user_name" name="user_name" class="form-control" value="<?= $model->user_name; ?>"/>
            </div>
            <div class="form-group">
                <label>Email</label>
                <input id="email" name="email" class="form-control" value="<?= $model->email; ?>"/>
            </div>
            <div class="form-group">
                <label>Текст задачи</label>
                <textarea rows="10" cols="45" id="text" name="text" class="form-control"><?= $model->text; ?></textarea>
            </div>
            <?php if($is_update):?>
                <div class="form-group">
                    <label>Статус</label>
                    <select class="form-control" id="id_status" name="id_status">
                        <?php foreach ($statusList as $value): ?>
                            <option value="<?= $value['id'] ?>"
                                    <?= $value['id'] === $model->id_status ? "selected" : "" ?>><?= $value['label']; ?></option>
                        <?php endforeach; ?>
                    </select>
                </div>
            <?php endif;?>
            <div class="form-group">
                <?php if (isset($error) && count($error) > 0): ?>
                    <div class="alert alert-danger">
                        <?php foreach ($error as $value): ?>
                            <span><?= $value; ?></span>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <?php if (isset($success) && count($success) > 0): ?>
                    <div class="alert alert-success">
                        <?php foreach ($success as $value): ?>
                            <span><?= $value; ?></span>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="form-group block-right">
                <div class="group-btn">
                    <a class="btn btn-outline-secondary" href="/">Главная</a>
                    <button type="submit" class="btn btn-primary"><?= !$is_update ? 'Добавить' : 'Обновить'; ?></button>
                </div>
            </div>
        </form>
    </div>
</div>
