<div class="form-input">
    <div class="bd-example">
        <form action="login" method="post" name="login">
            <h3>Авторизация</h3>
            <div class="form-group">
                <label>Имя пользователя</label>
                <input id="user_name" name="user_name" class="form-control" value="<?= $model->user_name; ?>"/>
            </div>
            <div class="form-group">
                <label>Пароль</label>
                <input id="password" name="password" type="password" class="form-control" value="<?= $model->password; ?>"/>
            </div>
            <div class="form-group">
                <?php if (isset($error) && count($error) > 0): ?>
                    <div class="alert alert-danger">
                        <?php foreach ($error as $value): ?>
                            <span><?= $value; ?></span>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
                <?php if (isset($success) && count($success) > 0): ?>
                    <div class="alert alert-success">
                        <?php foreach ($success as $value): ?>
                            <span><?= $value; ?></span>
                        <?php endforeach; ?>
                    </div>
                <?php endif; ?>
            </div>
            <div class="form-group block-right">
                <div class="group-btn">
                    <a class="btn btn-outline-secondary" href="/">Главная</a>
                    <button type="submit" class="btn btn-primary">Войти</button>
                </div>
            </div>
            <div class="form-group">
                <div class="alert alert-info" role="alert">
                    Тестовые данные admin/123
                </div>
            </div>
        </form>
    </div>
</div>
